

/* Create Tables */

-- Twitterのユーザーの情報を保存しているテーブル
CREATE TABLE USERS
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id',
	NAME VARCHAR(20) NOT NULL COMMENT 'ユーザーの名前',
	EMAIL VARCHAR(255) NOT NULL COMMENT 'ユーザーのメール',
	PASSWORD VARCHAR(255) NOT NULL COMMENT 'ユーザーのパスワード',
	DISPLAY_NAME VARCHAR(20) NOT NULL COMMENT '表示している名前',
	CREATED_AT DATETIME NOT NULL COMMENT 'created_at',
	UPDATED_AT DATETIME NOT NULL COMMENT 'updated_at',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'ユーザー : Twitterのユーザーの情報を保存しているテーブル';



/* Create Indexes */

CREATE UNIQUE INDEX UQ_USERS_NAME USING BTREE ON USERS (NAME ASC);
CREATE UNIQUE INDEX UQ_USERS_EMAIL USING BTREE ON USERS (EMAIL ASC);



